import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { jwtVerify } from "jose";
import type { AdminSession } from "@/lib/auth";
import type { AdminPermission } from "@/lib/models";
import { checkLoginRateLimit } from "@/lib/rate-limit";

const JWT_SECRET = new TextEncoder().encode(
  process.env.JWT_SECRET || "default-change-me-in-production"
);
const COOKIE_NAME = "rsp96_admin_session";

const routePermissions: Record<string, AdminPermission> = {
  "/admin/services": "services",
  "/admin/vacancies": "vacancies",
  "/admin/gallery": "gallery",
  "/admin/safescanget": "safescanget",
  "/admin/users": "users",
};

function getRequiredPermission(pathname: string): AdminPermission | null {
  for (const [prefix, permission] of Object.entries(routePermissions)) {
    if (pathname === prefix || pathname.startsWith(`${prefix}/`)) {
      return permission;
    }
  }
  return null;
}

function getClientIp(request: NextRequest): string {
  const forwarded = request.headers.get("x-forwarded-for");
  if (forwarded) {
    return forwarded.split(",")[0].trim();
  }
  return request.headers.get("x-real-ip") ?? "unknown";
}

const LOGIN_PATHS = new Set([
  "/login",
  "/login/",
  "/admin/login",
  "/admin/login/",
  "/api/auth/login",
  "/api/auth/login/",
]);

function isLoginPath(pathname: string): boolean {
  return LOGIN_PATHS.has(pathname);
}

// Patterns commonly used in reflected XSS / command-injection probes.
const SUSPICIOUS_QUERY_PATTERNS = [
  /<script\b/i,
  /javascript:/i,
  /on\w+\s*=/i,
  /<\s*iframe/i,
  /<\s*object/i,
  /<\s*embed/i,
  /;\s*echo\s+/i,
  /\|\s*echo\s+/i,
  /&&\s*echo\s+/i,
  /\|\|\s*echo\s+/i,
  /\$\(\s*echo\s+/i,
  /`\s*echo\s+/i,
];

function hasSuspiciousQueryParams(url: URL): boolean {
  for (const value of url.searchParams.values()) {
    for (const pattern of SUSPICIOUS_QUERY_PATTERNS) {
      if (pattern.test(value)) {
        return true;
      }
    }
  }
  return false;
}

function buildCspHeader(): string {
  const isDev = process.env.NODE_ENV === "development";
  return [
    "default-src 'self'",
    `script-src 'self' 'unsafe-inline'${isDev ? " 'unsafe-eval'" : ""} https://mc.yandex.ru https://yandex.ru`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: https:",
    "font-src 'self'",
    "connect-src 'self' https://mc.yandex.ru https://yandex.ru wss://mc.yandex.ru",
    "frame-ancestors 'self'",
    "base-uri 'self'",
    "form-action 'self'",
  ].join("; ");
}

export async function proxy(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Block common injection probes in query parameters before they are reflected.
  if (request.method === "GET" && hasSuspiciousQueryParams(request.nextUrl)) {
    return new NextResponse("Bad Request", { status: 400 });
  }

  // Rate-limit all login endpoints to mitigate brute-force and credential-stuffing.
  if (isLoginPath(pathname)) {
    if (pathname.startsWith("/api/") && request.method !== "POST") {
      return new NextResponse("Method Not Allowed", { status: 405 });
    }
    const ip = getClientIp(request);
    const { allowed, retryAfter } = checkLoginRateLimit(ip);
    if (!allowed) {
      return new NextResponse("Too Many Requests", {
        status: 429,
        headers: { "Retry-After": String(retryAfter) },
      });
    }
  }

  // Protect all /admin routes except /admin/login
  if (pathname.startsWith("/admin") && pathname !== "/admin/login/" && pathname !== "/admin/login") {
    const token = request.cookies.get(COOKIE_NAME)?.value;

    if (!token) {
      return NextResponse.redirect(new URL("/admin/login/", request.url));
    }

    let session: AdminSession | null = null;
    try {
      const { payload } = await jwtVerify(token, JWT_SECRET);
      session = payload as unknown as AdminSession;
    } catch {
      return NextResponse.redirect(new URL("/admin/login/", request.url));
    }

    const required = getRequiredPermission(pathname);
    if (required) {
      if (session.role !== "superadmin" && !session.permissions.includes(required)) {
        return NextResponse.redirect(new URL("/admin/", request.url));
      }
    }
  }

  // Apply a CSP that allows the inline scripts/styles generated by Next.js and
  // the Yandex Metrika integration. A fully nonce-based policy requires the
  // framework nonce to be propagated from the rendering layer, which is left as
  // a future hardening step.
  const csp = buildCspHeader();
  const response = NextResponse.next();
  response.headers.set("Content-Security-Policy", csp);

  return response;
}

export const config = {
  matcher: [
    {
      source: "/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml).*)",
      missing: [
        { type: "header", key: "next-router-prefetch" },
        { type: "header", key: "purpose", value: "prefetch" },
      ],
    },
  ],
};
